title: Chintha Srikar
title: '**Contact:** +1 716-907-7718 | [srikarchintha444@gmail.com](mailto:srikarchintha444@gmail.com) | [LinkedIn](www.linkedin.com/in/chinthasrikar444)'
logo: /SrikarProfile.jpg
show_downloads: true
theme: jekyll-theme-minimal
